In [1]:
from loaddata import BTMF

In [2]:
import numpy as np

In [3]:
mat = np.random.rand(10, 12)

In [5]:
bina = np.random.choice(2, size=mat.shape, p=[0.3, 0.7])

In [6]:
bina

array([[0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
       [1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [7]:
sparseMat = mat * bina

In [8]:
sparseMat.round(2)

array([[0.  , 0.21, 0.  , 0.26, 0.  , 0.95, 0.  , 0.62, 0.6 , 0.  , 0.47,
        0.33],
       [0.  , 0.  , 0.  , 0.38, 0.  , 0.78, 0.22, 0.61, 0.33, 0.  , 0.34,
        0.  ],
       [0.19, 0.  , 0.04, 0.68, 0.85, 0.8 , 0.46, 0.  , 0.  , 0.34, 0.  ,
        0.24],
       [0.9 , 0.43, 0.9 , 0.95, 0.  , 0.  , 0.  , 0.29, 0.2 , 0.41, 0.  ,
        0.  ],
       [0.  , 0.74, 0.27, 0.  , 0.14, 0.61, 0.  , 0.87, 0.54, 0.24, 0.41,
        0.02],
       [0.81, 0.  , 0.89, 0.68, 0.14, 0.  , 0.54, 0.11, 0.  , 0.  , 0.47,
        0.11],
       [0.  , 0.68, 0.  , 0.66, 0.49, 0.52, 0.73, 0.72, 0.58, 0.  , 0.4 ,
        0.  ],
       [0.07, 0.  , 0.  , 0.  , 0.  , 0.01, 0.6 , 0.81, 0.84, 0.86, 0.02,
        0.28],
       [0.37, 0.  , 0.92, 0.65, 0.06, 0.08, 0.  , 0.  , 0.  , 0.14, 0.  ,
        0.29],
       [0.86, 0.  , 0.  , 0.35, 0.74, 0.55, 0.89, 0.5 , 0.9 , 0.12, 0.03,
        0.13]])

In [10]:
dim1, dim2 = sparseMat.shape
rank = min(dim1, dim2) // 2
init = {"W": 0.1 * np.random.rand(dim1, rank), "X": 0.1 * np.random.rand(dim2, rank)}
time_lags = np.array([1, 2, 3])
newMat, W, X, A = BTMF(mat, sparseMat, init, rank, time_lags, 1100, 100)

In [11]:
newMat.round(2)

array([[ 0.44,  0.21,  0.83,  0.26,  0.98,  0.95, -0.1 ,  0.62,  0.6 ,
        -1.24,  0.47,  0.33, -1.64],
       [ 0.55,  0.55,  0.35,  0.38, -0.33,  0.78,  0.22,  0.61,  0.33,
        -0.52,  0.35, -0.16, -0.58],
       [ 0.19,  1.22,  0.04,  0.68,  0.85,  0.8 ,  0.46,  1.86,  1.15,
         0.34,  0.64,  0.24, -1.29],
       [ 0.9 ,  0.43,  0.9 ,  0.95,  0.27,  0.65,  0.86,  0.29,  0.2 ,
         0.41,  0.58,  0.19,  1.08],
       [ 0.48,  0.74,  0.27,  0.59,  0.14,  0.61,  0.54,  0.87,  0.54,
         0.24,  0.41,  0.02, -0.16],
       [ 0.81,  0.24,  0.89,  0.68,  0.14,  0.69,  0.54,  0.11,  0.11,
        -0.18,  0.47,  0.11,  0.55],
       [ 0.58,  0.67,  0.45,  0.67,  0.49,  0.53,  0.73,  0.72,  0.57,
         0.47,  0.4 ,  0.17,  0.18],
       [ 0.08,  0.65, -0.1 ,  0.23,  1.  ,  0.01,  0.6 ,  0.81,  0.84,
         0.86,  0.02,  0.28, -0.34],
       [ 0.37, -0.63,  0.92,  0.65,  0.06,  0.08,  0.15, -0.83, -0.82,
         0.14,  0.51,  0.29,  2.01],
       [ 0.85,  0.7 ,  0.57,

In [6]:
import numpy as np
a = np.zeros((2,3))
a.nonzero()

(array([], dtype=int64), array([], dtype=int64))

In [10]:
b = np.ones((2, 3))
ind = b[:, 0].nonzero()

In [25]:
c = np.array([0.5, 0., 2])

In [26]:
c[c == 0] = 1

In [27]:
c

array([0.5, 1. , 2. ])

In [18]:
print(b[0, 1].item())

1.0


In [13]:
from scipy.interpolate import interp1d

In [15]:
f = interp1d([1, 2], [6, 8], kind='nearest')
print(f([1,2,3,4,5]))

ValueError: A value in x_new is above the interpolation range.